language: bash
install:
  - sudo apt-get install ksh zsh -y
before_script:
  - curl -o /tmp/urchin https://raw.github.com/scraperwiki/urchin/master/urchin && chmod +x /tmp/urchin
script:
  - NVM_DIR=$TRAVIS_BUILD_DIR make URCHIN=/tmp/urchin test
